[credentials]
bot_token = your_bot_token_here
openai_like_api_key = your_OpenAI_API_key_here
gemini_api_key = your_Gemini_API_key_here
gemini_proxy_url = your_Gemini_proxy_url_here
nai_username = your_NovelAI_username_here
nai_password = your_NovelAI_password_here

[customizations]
bot_name = Luna
bot_activity = eating tacos 🌮
embed_footer = Don't trust Luna.
wait_message = Don't worry ✋

[settings]
; if multiple prefixes, use space to separate them. example: "! * ="
command_prefix = !
; if you don't display confirmation, then what ever delete & seconds is set to doesn't matter
display_confirmation = True
delete_confirmation = True
seconds_before_deleting_confirmation = 5
; make sure you don't delete the invocation if you want bot to reply to you
reply = True
mention_author = True
delete_invocation = False
; sets whether only the invoker can see the reply
ephemeral = False

[paint_settings]
paint_backend = comfyui
comfyui_url = 127.0.0.1:8188
comfyui_workflow_folder = comfyui_workflows
workflow = SDXL_exmaple.json
paint_timeout = 600

[tts_settings]
; settings for BanG Dream text-to-speech
; https://huggingface.co/spaces/Mahiruoshi/BangDream-Bert-VITS2
speaker = 香澄

[chat_settings]
chat_backend = gemini
temperature = 0.9
top_p = 0.9
top_k = 50
max_new_tokens = 256
model = gemini-1.5-flash
context_limit = 20
context_keep = 2
timeout = 60
system_prompt = config/system_prompt.txt
summarize_prompt = config/summarize_prompt.txt
jailbreak_prompt = config/jailbreak_prompt.txt
